services:
  react-app:
    build:
      dockerfile: ./docker/react-app/Dockerfile
    container_name: react-app
    command: make run
    ports:
      - 8080:8080
    volumes:
      # Exclude container directory overwritten by host.
      - /react-app/node_modules
      # Then, mount host volume.
      - ./react-app:/react-app

  vue-app:
    build:
      dockerfile: ./docker/vue-app/Dockerfile
    container_name: vue-app
    command: make run
    ports:
      - 8081:8081
    volumes:
      # Exclude container directory overwritten by host.
      - /vue-app/node_modules
      # Then, mount host volume.
      - ./vue-app:/vue-app
