name: Lint
on:
  push:
    tags:
      - '20[0-9][0-9]-[0-1][0-9]-[0-3][0-9] [0-9]+.[0-9]+.[0-9]+'  # Matches YYYY-MM-DD X.Y.Z

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: pnpm i
      - run: pnpm lint
